text = open('alice.txt', 'r')   # open the file for reading

alpha_dash = "abcdefghijklmnopqrstuvwxyz-"  # string of all alphabetic characters and "-"

count = {}  # create an empty dictionary to keep count of each word
for line in text:   # loop that goes line by line on the text opened
    for word in line.split():   # loop that goes item by item on the list generated by splitting the string of the line
        word = word.lower()  # convert each string item to lowercase
        clean_word = ""  # create an empty string for the cleaned-up version of the word
        for i in word:  # loop to run through character of the unprocessed word
            if i in alpha_dash:  # if the character is in our filtering list, then add to the cleaned-up version
                clean_word += i
        if clean_word not in ("", "-"):   # if the clean word is not empty or a single dash, update the count
            if clean_word in count:
                count[clean_word] += 1
            else:
                count[clean_word] = 1

keys = sorted(count.keys())

output_file = open('alice_words.txt', 'w')

for k in keys:
    output_file.write(k + "\t" + str(count[k]) + "\n")

longestkey = keys[0]

for k in keys:
    if len(k) > len(longestkey):
        longestkey = k

print("The longest word in Alice in the Wonderlands is: " + longestkey + " with " + str(len(longestkey)) + " characters")
